# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.17.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # ensure_git_status_clean 
    
  end

  desc "Build the documentation"
  lane :doc do |options|
    scheme = options[:scheme]
    appledoc(
      project_name: "#{scheme}",
      project_company: "Sage Bionetworks",
      input: "#{scheme}",
      output: "./Documentation",
      options: "--keep-intermediate-files --search-undocumented-doc",
      warnings: "--warn-missing-output-path --warn-missing-company-id"
    )
  end

  desc "Run tests"
  lane :test do |options|
    scheme = options[:scheme]
    build_for_testing = options[:build_for_testing]
    only_testing = '"BridgeSDKTests","BridgeSDKIntegrationTests"'

    if options[:only_testing]
       only_testing = options[:only_testing]
    end

    if build_for_testing
       scan(
         scheme: "#{scheme}",
         build_for_testing: true
       )
    else
       scan(
         scheme: "#{scheme}",
         only_testing: "#{only_testing}",
         xcargs: [
           'SAGE_ADMIN_EMAIL=$SAGE_ADMIN_EMAIL',
           'SAGE_ADMIN_PASSWORD=$SAGE_ADMIN_PASSWORD']
        )
    end
  end


  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
